spring.application.name=FINTRACK

spring.datasource.url=jdbc:mysql://localhost:3306/fintrack
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret= FinTrackJwtSecretKeyForDevelopmentOnly2026VeryLong
jwt.expiration=3600000